### ISSUE TITLE
Week 12 Update

### ISSUE THREAD

**Issue by carletonb** [gw-sd-2016/crimedata#2]
This week, I applied fixes to the mapping interface, designed to limit the data returned to the client to only those incidents that can be displayed within the current bounding box of the map. When the map is dragged, changing the bounding box, the client sends the new coordinates (of the NW and SE corners) to the server, which then returns an updated dataset. As a result of this, I was able to re-insert the entire Chicago 2015 dataset (>200k rows), and the map is now actually usable. I still need to make changes to further limit the data returned at high zoom levels because depending on the precise location, there may still be a huge amount of incidents even at the maximum zoom limit (i.e., the map zoomed out as far as we allow).

I have also begun trying to implement the spatial autocorrelation algorithm. At this point, I am still going through the math on paper before I begin writing code.

 @cctoombs and @twood02

**Comment by twood02** [comment]
sounds good.  make an effort to get a good chunk of the algorithm working before the end of the semester---your project will be much more impressive once it is doing some kind of analysis rather than just providing a UI for data.
