### ISSUE TITLE
Week 20 - Algorithm implementation

### ISSUE THREAD

**Issue by benca** [gw-sd-2016/crimedata#5]
At this point, the application is able to produce the inputs to the spatial autocorrelation algorithm and display the output on the map. Most importantly, the results of the analysis using inputs generated by the application are _functionally identical_ to the results shown when using the inputs supplied with the example data, validating the methods by which we are generating that information. I'll be able to compare the sample inputs to my generated inputs during the demo on Wednesday. 

I also made some changes to the way the map handles what I'm calling "subdivisions" -- that is, the boundary areas that we are using as stand-ins for counties since GW's campus is obviously not subdivided into counties. To achieve this, I am reading in a dataset published by the DC Government which provides GIS polygons for each block in the city:

![dcsquares](https://cloud.githubusercontent.com/assets/1020118/12404517/40d655fc-be0a-11e5-8228-64d05a938cf0.png)

There are also some changes to the way these subdivisions are rendered on the map -- the client now only loads those subdivisions which are visible in the map's bounding box.

The most important step going forward is now getting the GWPD data read in so we can run the analysis against that data.

@twood02 @cctoombs

**Comment by carletonb** [comment]
(also, sorry about opening that issue using the wrong account...)

**Comment by twood02** [comment]
For your 70% demo be sure you can explain the meaning of your auto
correlation algorithm---when you run it on the GW crime data set what will
it actually signify?

Let me know if you want to meet this week.

## 

---

Timothy Wood, Ph. D.
Assistant Professor
Department of Computer Science
The George Washington University
http://www.seas.gwu.edu/~timwood
