### ISSUE TITLE
Week 21 - User-selectable date range

### ISSUE THREAD

**Issue by carletonb** [gw-sd-2016/crimedata#6]
This week I implemented functionality which allows the end-user to select the date range to run the analysis against. I am also working on the import of the GWPD data, where I am in the process of assembling lookup tables to use with location data as well as the crime type, which is not consistent throughout the different records. Once I have completed this, I will be able to import the data and run the spatial autocorrelation analysis against it. Also, I'll be able to use this to build the import method that will be used by the end-users to import additional data in the future.

@twood02 @cctoombs

**Comment by twood02** [comment]
ok, let's plan to meet sometime this week so you can show me your 70% demo and we can discuss your plans. I'll send out a list of meeting times tomorrow.
