### ISSUE TITLE
Week 22 - GWPD data

### ISSUE THREAD

**Issue by carletonb** [gw-sd-2016/crimedata#7]
This week, I worked on getting the GWPD data into the database. I manually inserted the first group of records to determine the feasibility of running the spatial autocorrelation algorithm against it. Aside from one minor change I need to make with respect to the inputs to the algorithm related to the weights matrix, it looks like it will be OK (this is because the city block polygons we're using as stand-ins for counties don't touch on their edges, while the counties used on the library's demo data do). I also started working on the import tool that will allow us to read in the rest of the spreadsheet programatically, so that we don't have to manually key in >10,000 rows.

@twood02 @cctoombs

**Comment by twood02** [comment]
ok, let's get this going ASAP so we can be sure your tool will be able to provide some sort of meaningful results.  If you want to meet with me pick a time here: https://calendly.com/timwood/meetings/02-01-2016
