### ISSUE TITLE
Week 23 - GWPD Data II

### ISSUE THREAD

**Issue by carletonb** [gw-sd-2016/crimedata#8]
This week I made more progress with the automated GWPD data import process. At this point, the only thing I need to do with it is finish implementing the building name to lat/lon lookup, and then we will be able to begin processing the GWPD data into the spatial autocorrelation algorithm.

Prof Wood, if you're available to meet on Thursday or Friday of this week, I'd like to be able to show you that result.

@twood02 @cctoombs

**Comment by twood02** [comment]
pick a time slot here: https://calendly.com/timwood/meetings/02-08-2016
