### ISSUE TITLE
Week 24 - GWPD data imported

### ISSUE THREAD

**Issue by carletonb** [gw-sd-2016/crimedata#9]
As we discussed on Friday, we now have the GWPD data import working, and we can now run the spatial autocorrelation algorithm against this data. Now, we must get the rest of the data imported and continue to fine-tune the algorithm's input parameters. I'm going to investigate shading the hotspots on the map (which are currently binary), as well as investigate how we can subdivide the campus into areas smaller than blocks. I'm also going to work on improving the location alias geocoding function by trying to match on the parsed display name _and_ the GPS coordinates returned by the Google geocode API.

@twood02 @benca

**Comment by twood02** [comment]
If you want to meet again this week sign up here: https://calendly.com/timwood/meetings/02-17-2016
